before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq doxygen cppcheck g++-4.8
 - alias gcc="gcc-4.8"
 - alias g++="g++-4.8"
 - alias gcov="gcov-4.8"

language: cpp

compiler:
 - gcc

script: 
 - cd build
 - python build.py nightly expand_logs=1

