before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq doxygen cppcheck libc++-dev g++-4.8

language: cpp
compiler:
 - clang
 - gcc
script: 
 - cd build
 - python build.py nightly expand_logs=1
 - python build.py nightly clang_build=1 expand_logs=1

