import SCons.Defaults
import SCons
from SCons.Util import unique
import glob
import sys

baseDir = "../../"
sys.path.append(baseDir) #Get globals
from Globals import *
from SConstructGlobals import *
from SethCommonGlobals import *

#Make Common environment
projectName = "Debug New"
targetFlags = CREATE_LIB_TARGET
envBase = createBaseEnvironment(baseDir, baseDir, projectName, targetFlags, ARGUMENTS)

Help(getHelpMessage(envBase))

#Make commonCXX environment
CXXEnvironment = createDebugEnvironment(envBase, [], [], [])
if (envBase['MSVC_BUILD']):
    CXXEnvironment['CCFLAGS'].remove('/WX')
else:
    CXXEnvironment['CCFLAGS'].remove('-Werror')
    CXXEnvironment['CCFLAGS'].remove('-pedantic-errors')

CXXEnvironment['LIBDIR'] = os.path.join(libDir, CXXEnvironment['SYSTEM'], CXXEnvironment['LIB_TYPE'])

if (envBase['SHARED_BUILD']):
    debugNewObject = CXXEnvironment.SharedObject(glob.glob('*.cpp'))
else:
    debugNewObject = CXXEnvironment.Object(glob.glob("*.cpp"))

buildDebugNew = createLib(CXXEnvironment, "debug_new", debugNewObject)

Alias(CREATE_LIB_ALIAS, buildDebugNew)
Alias(DOXYGEN_ALIAS, [])

Alias(DELTA_ALIAS, buildDebugNew)
Alias(NIGHTLY_ALIAS, buildDebugNew)

Default(CREATE_LIB_ALIAS)

