import SCons.Defaults
import SCons
from SCons.Util import unique
import glob
import sys

baseDir = "../../"
sys.path.append(baseDir) #Get globals
from Globals import *
from SConstructGlobals import *
from SkyvoCommonGlobals import *

#Make Common environment
projectName = "Debug New"
targetFlags = CREATE_LIB_TARGET
envBase = createBaseEnvironment(baseDir, baseDir, projectName, targetFlags, ARGUMENTS)

Help(getHelpMessage(envBase))

#Make commonCXX environment
CXXEnvironment = createDebugEnvironment(envBase, [], [], [])
if (envBase['MSVC_BUILD']):
    CXXEnvironment['CCFLAGS'].remove('/WX')
else:
    CXXEnvironment['CCFLAGS'].remove('-Werror')
    CXXEnvironment['CCFLAGS'].remove('-pedantic-errors')

CXXEnvironment['LIBDIR'] = os.path.join(libDir, CXXEnvironment['SYSTEM'])

debugNewObject = CXXEnvironment.Object(glob.glob("*.cpp"))

buildDebugNew = createStaticLib(CXXEnvironment, "debug_new", debugNewObject)

Alias("create_lib", buildDebugNew)
Alias("doxygen", [])

Alias("delta", buildDebugNew)
Alias("nightly", buildDebugNew)

Default("create_lib")

