import SCons.Defaults
import SCons
from SCons.Util import unique
import sys

baseDir = "../../"
sys.path.append(baseDir) #Get globals
from Globals import *
from SConstructGlobals import *
from SkyvoCommonGlobals import *

envBase = createBaseEnvironment(baseDir, ARGUMENTS)

#Make commonCXX environment
CXXEnvironment = createDebugEnvironment(envBase, [], [], [])
CXXEnvironment['CCFLAGS'] = ['-g', '-std=gnu++11']
CXXEnvironment['LIBDIR'] = os.path.join(libDir, CXXEnvironment['SYSTEM'])
addPlatformFlags(CXXEnvironment)

debugNewObject = CXXEnvironment.Object("debug_new.cpp")

buildDebugNew = createStaticLib(CXXEnvironment, "debug_new", debugNewObject)

Alias("create_lib", buildDebugNew)

Default("create_lib")