import SCons.Defaults
import SCons
from SCons.Util import unique
import stat
import os
import sys
import subprocess
import glob
import shutil
from copy import deepcopy

baseDir = os.path.abspath("../../")
sys.path.append(baseDir) #Get globals
from Globals import *
from SConstructGlobals import parseArguments

armBuild = parseArguments(ARGUMENTS)

from SConstructGlobals import *

###
# Files to compile
###

###include paths:
includePaths = [includeDir]
testIncludePaths = [os.path.join(testDir, includeDir)]

###Source Files
sourceFiles = glob.glob(os.path.join(srcDir, "*.cpp"))
sourceTestFiles = glob.glob(os.path.join(testDir, "*.cpp")) + glob.glob(os.path.join(testDir, srcDir, "*.cpp"))
coverageFiles = deepcopy(sourceFiles)
    
###Libs
libs = []

###libPath
libPath = []

Help(
'''
SConstruct file for SCSV project

Targets:
    debug          Builds the project for Debug lib (Default)
    release        Builds the project for Release lib
    create_lib     Builds both the debug and release libs
    doxygen        Builds the doxygen documentation
    unit_test      Builds the project for Unit Tests
    run_test       Builds and runs the Unit Tests and memcheck and coverage
'''
)

###
# Environment creation
###

#Make common environment
envBase = createBaseEnvironment(baseDir, armBuild)

#Debug Environment
debugEnvironment = createDebugEnvironment(envBase, includePaths, libs, libPath)

#Release Environment
releaseEnvironment = createReleaseEnvironment(envBase, includePaths, libs, libPath)

#Unit test environment
testEnvironment = createUnitTestEnvironment(envBase, includePaths + testIncludePaths, libs, libPath)

###Doxygen
doxygenFiles = sourceFiles + sourceTestFiles + glob.glob(os.path.join(includeDir, "*h")) + glob.glob(os.path.join(testDir, includeDir, "*h"))

###
# Test outputs
###
createTestOutputFolder(envBase)
    
###
# Targets
###

debugTarget = createStaticLib(debugEnvironment, "SCSV-d", sourceFiles)
releaseTarget = createStaticLib(releaseEnvironment, "SCSV", sourceFiles)
(unitTestTarget, runTestTarget) = createUnitTestExe(testEnvironment, sourceFiles + sourceTestFiles, coverageFiles, armBuild)
doxygenTarget = createDoxygenTarget(envBase, doxygenFiles)

Alias("debug", debugTarget)
Alias("release", releaseTarget)
Alias("create_lib", ["debug", "release"])
Alias("doxygen", doxygenTarget)
Alias("unit_test", unitTestTarget)
Alias("run_unit_test", runTestTarget)
Alias("run_test", [unitTestTarget, runTestTarget])

#used by auto build
if (armBuild):
    print("WARNING! Unit tests are not going to be run on an ARM nightly/delta build")
    Alias ("nightly", ["create_lib", "doxygen", "unit_test"])
    Alias ("delta", ["create_lib", "unit_test"])
else:
    Alias ("nightly", ["create_lib", "doxygen", "run_test"])
    Alias ("delta", ["create_lib", "run_test"])

Default(["debug"])
