import SCons.Defaults
import SCons
from SCons.Util import unique
import stat
import os
import sys
import subprocess
import glob
import shutil
from copy import deepcopy

baseDir = "../../"
sys.path.append(baseDir) #Get globals
from Globals import *
from SConstructGlobals import *

projectName = "gmock"
targetFlags = CREATE_LIB_TARGET
envBase = createBaseEnvironment(baseDir, baseDir, projectName, targetFlags, ARGUMENTS)

#include paths
includePaths = ["include"]

#source files
sourceFiles = ['src/gmock-gtest-all.cc']
testSourceFiles = []

    
#Libs
libs = []

#libPath
libPath = []

#link flags
linkFlags = []

Help(getHelpMessage(envBase))

###
# Environment creation
###
libEnvironment = createDebugEnvironment(envBase, includePaths, libs, libPath)
#Override flags
if (envBase['CLANG_BUILD']):
    libEnvironment.Append(CPPDEFINES = ['GTEST_USE_OWN_TR1_TUPLE=1'])

if (envBase['MSVC_BUILD']):
    libEnvironment['CCFLAGS'].remove('/WX')
else:
    libEnvironment['CCFLAGS'].remove('-Werror')
    libEnvironment['CCFLAGS'].remove('-pedantic-errors')

libEnvironment['LIBDIR'] = os.path.join(libDir, envBase['SYSTEM'], envBase['LIB_TYPE'])

#Doxygen 
doxygenFiles = sourceFiles + testSourceFiles + glob.glob(os.path.join(includeDir, "*h")) +  glob.glob(os.path.join(includeDir, "*", "*h"))

###
# Targets
###
libBuild  = createLib(libEnvironment, "gmock", sourceFiles)

Alias("create_lib", libBuild)
Alias("doxygen", [])

Alias ("nightly", ["create_lib"])
Alias ("delta", ["create_lib"])

Default("create_lib")
